config/routes.rb
Rails.application.routes.draw do
  resources :event_attachments
  devise_for :users
  root to: 'pages#home'
  resources :events
  resources :bios, only: [:index, :new, :create, :edit, :update, :destroy]
  get '/contact', to: 'pages#contact', as: 'contact'
  resources :attachments, only: [:index, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  has_one_attached :photo, dependent: :destroy
  has_many :catalogs
  has_many :events, through: :catalogs
end

app/models/bio.rb
class Bio < ApplicationRecord
end

app/models/catalog.rb
class Catalog < ApplicationRecord
  belongs_to :events
  belongs_to :attachments
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :catalogs
  has_many :attachments, through: :catalogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  require 'mini_magick'
  def index
    @attachments = Attachment.all
  end

  def show
    find_attachment
  end

  def new
    @attachment = Attachment.new
  end

  def create
    @attachment = Attachment.new(attachment_params)
      MiniMagick::Image.new(params[:attachment][:photo].tempfile.path).resize('800x800')
    if @attachment.save
      flash.notice = "CREATED"
      redirect_to attachments_path
    else
      render :new
    end
  end

  def edit
    find_attachment
  end

  def update
    find_attachment
    if @attachment.update(attachment_params)
      flash.notice = "UPDATED"
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    find_attachment
    @attachment.destroy
    flash.alert = "DELETED"
    redirect_to events_path
  end

  private

  def attachment_params
    params.require(:attachment).permit(:caption, :photo)
  end

  def find_attachment
    @attachment = Attachment.find(params[:id])
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @bios = Bio.all
  end

  def new
    @bio = Bio.new
  end

  def create
    @bio = Bio.new(bio_params)
    if @bio.save
      flash.notice = "CREATED"
      redirect_to bios_path
    else
      render :new
    end
  end

  def edit
    find_bio
  end

  def update
    find_bio
    if @bio.update(bio_params)
      flash.notice = "UPDATED"
      redirect_to bios_path
    else
      render :edit
    end
  end

  def destroy
    find_bio
    @bio.destroy
    flash.notice = "DELETED"
    redirect_to bios_path
  end

  private

  def bio_params
    params.require(:bio).permit(:title, :bioyear, :institute, :place)
  end

  def find_bio
    @bio = Bio.find(params[:id])
  end
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
    @catalog = Catalog.new
  end

  def create
    @catalog = Catalog.new(catalog_params)
    @event = Event.find(params[:event_id])
    @catalog.event = @event
    if @catalog.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def destroy
    @catalog = Catalog.find(params[:id])
    @catalog.destroy
    redirect_to event_path(@catalog[:event_id])
  end

  private

  def catalog_params
    params.require(:catalog).permit(:event_id, :attachment_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  require 'mini_magick'
  require 'catalog'
  require 'attachment'
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @events = Event.all
  end

  def show
    find_event
    @catalog = Catalog.where(event_id: @event)
  end

  def new
    @catalog = Catalog.all
    @attachments = Attachment.all
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash.notice = "CREATED"
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
    find_event
  end

  def update
    find_event
    if @event.update(event_params)
      flash.notice = "UPDATED"
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    find_event
    @event.destroy
    flash.alert = "DELETED"
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :eventtext, :eventdate, :links, :photos => [])
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def find_attachment
    @attachment = Attachment.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :contact]
  def home
    @events = Event.all
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attachments/index.html.erb
<%= render 'shared/navbar' %>
<br>
  <div class="container">
      <div class="cards">
        <% @attachments.each do |attachment| %>
            <% if attachment.photo.attached? %>
                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= cl_image_path attachment.photo.key %>)">
                  <p class="cardtext"> <%= attachment.caption %> </p>
                  <% if user_signed_in? %>
                    <button type="button" class="btn btn-light" > <%= link_to "EDIT", edit_attachment_path(attachment) %> </button>
                    <button type="button" class="btn btn-danger"> <%= link_to "DEL", attachment_path(attachment), method: :delete, data: { confirm: "SURE?" } %></button>
                  <% end %>
                </div>
            <% else %>
                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4))">
                  <p class="cardtext"> <%= attachment.caption %> </p>
                  <% if user_signed_in? %>
                    <button type="button" class="btn btn-light" > <%= link_to "EDIT", edit_attachment_path(attachment) %> </button>
                    <button type="button" class="btn btn-danger"> <%= link_to "DEL", attachment_path(attachment), method: :delete, data: { confirm: "SURE?" } %></button>
                  <% end %>
                </div>
            <% end %>
        <% end %>
      </div>
  </div>
  <% if user_signed_in? %>
  <div>
    <%= link_to "ADD 1", new_attachment_path, class: "btn btn-gradient" %>
  </div>
  <% end %>

app/views/attachments/new.html.erb
<%= render 'shared/navbar' %>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="costume-form p-4 mt-4 mb-4">
        <h2>Add a new Attachment</h2>

        <%= simple_form_for [@attachment] do |f| %>
          <%= f.label :photo %>
          <%= f.file_field :photo %>
          <%= f.input :caption %>
          <br>
          <%= f.button :submit, "Add Attachment", class: "btn btn-success" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/bios/index.html.erb
<%= render 'shared/navbar' %>
<div class="container ml-0">
  <div class= 'banner'></div>
  <br>
  <div>
    <ul>
      <div class="cards">
        <ul>
          <% @bios.each do |bio| %>
            <li> <%= bio.bioyear %>  |  <%= bio.title %>  |  <%= bio.institute %>  |  <%= bio.place %> </li>
              <div class="grid-item">
                <% if user_signed_in? %>
                  <button type="button" class="btn btn-light"> <%= link_to "EDIT", edit_bio_path(bio) %> </button>
                  <button type="button" class="btn btn-danger"> <%= link_to "DEL", bio_path(bio), method: :delete, data: { confirm: "SURE?" } %> </button>
                <% end %>
              </div>
        <% end %>
      </ul>
      </div>
    </ul>
  </div>
  <% if user_signed_in? %>
  <div>
    <%= link_to "ADD 1", new_bio_path, class: "btn btn-gradient" %>
  </div>
  <% end %>
</div>

app/views/bios/new.html.erb
<%= render 'shared/navbar' %>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="costume-form p-4 mt-4 mb-4">
        <h2>ADD NU BIO</h2>
        <%= simple_form_for [@bio] do |f| %>
          <%= f.input :bioyear %>
          <%= f.input :title %>
          <%= f.input :institute %>
          <%= f.input :place %>
          <%= f.input :category, :collection => ['Solo Exhibition', 'Group Exhibition', 'Awards'] %>
          <br>
          <%= f.button :submit, "ADD", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<%= render 'shared/navbar' %>
<br>
<div class='container'>

    <%= form_tag events_path, method: :get do %>
      <div class='search'>
        <%= text_field_tag :query, params[:query], class: "form-control"%>
        <%= button_tag type: 'submit', class: "btn btn-outline-primary postfix ml-1" do %>
          <i class="fas fa-search" aria-hidden="true"></i>
        <% end %>
      </div>
    <% end %>

</div>
  <br>
  <div class="container">
      <div class="cards">
        <% @events.each do |event| %>
            <% if event.attachments.first.photo.attached? %>
                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= cl_image_path event.attachments.first.photo.key %>)">
                  <h1 class="cardtext"><strong> <%= link_to event.title, event_path(event), class: "" %> </strong></h1>
                  <p class="cardtext"> <%= event.eventdate %> </p>
                  <% if user_signed_in? %>
                    <button type="button" class="btn btn-light" > <%= link_to "EDIT", edit_event_path(event) %> </button>
                    <button type="button" class="btn btn-danger"> <%= link_to "DEL", event_path(event), method: :delete, data: { confirm: "SURE?" } %></button>
                  <% end %>
                </div>
            <% else %>
                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4))">
                  <h1><strong> <%= link_to event.title, event_path(event), class: "" %> </strong></h1>
                  <p> <%= event.eventdate %> </p>
                  <% if user_signed_in? %>
                    <button type="button" class="btn btn-light" > <%= link_to "EDIT", edit_event_path(event) %> </button>
                    <button type="button" class="btn btn-danger"> <%= link_to "DEL", event_path(event), method: :delete, data: { confirm: "SURE?" } %></button>
                  <% end %>
                </div>
            <% end %>
        <% end %>
      </div>
  </div>
  <% if user_signed_in? %>
  <div>
    <%= link_to "ADD 1", new_event_path, class: "btn btn-gradient" %>
  </div>
  <% end %>

app/views/events/new.html.erb
<%= render 'shared/navbar' %>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="costume-form p-4 mt-4 mb-4">
        <h2>Add a new Event</h2>

        <%= simple_form_for [@event] do |f| %>
          <%= f.input :title %>
          <%= f.input :eventtext %>
          <%= f.input :eventdate %>
          <%= f.input :links %>
          <%= f.association :attachments, collection: @attachments, input_html: { multiple: true } %>
          <br>
          <%= f.button :submit, "Add Event", class: "btn btn-success" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<%= render 'shared/navbar' %>
<br>
<div class= "container">
  <% if Attachment.includes(@event).count > 1 %>
    <div id="carouselExampleControls" class="carousel slide carousel-fade" data-interval="false" data-bs-interval="false">
      <div class="carousel-inner">
        <% @event.attachments.each_with_index do |attachment,i| %>
          <div class="carousel-item <%= "active" if i==0 %>" style="background-image: url(<%= cloudinary_url(attachment.photo.key) %>)" ></div>
        <% end %>
      </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-button"><</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-button">></span>
        </a>
    </div>
  <% elsif Attachment.includes(@event).count == 1 %>
    <div id="carouselExampleControls" class="carousel slide carousel-fade" data-interval="false" data-bs-interval="false">
      <div class="carousel-inner">
        <% @event.attachments.each_with_index do |attachment,i| %>
          <div class="carousel-item <%= "active" if i==0 %>" style="background-image: url(<%= cloudinary_url(attachment.photo.key) %>)" ></div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="show-image mb-3 d-flex justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)); color: rgba(0,0,0,0.5)">
      <p><em>No image uploaded.</em></p>
    </div>
  <% end %>
  <br>
  <br>
  <div class="eventtext">
    <h2><%= @event.title %></h2>
    <p><%= @event.eventtext %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JPHP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
<%= render 'shared/flashes' %>

app/views/pages/contact.html.erb
<%= render 'shared/navbar' %>
<div class="position-absolute translate-middle">
<h1>jo@jopenca.com</h1>
</div>

app/views/pages/home.html.erb
<div class="container">
    <div class="logo mb-5" class="mb-5">
    </div>
      <div>
        <%= link_to "JOPENCA.COM", root_path, class: "btn btn-success my-1" %>
      </div>
      <div>
        <%= link_to "NEWS", events_path, class: "btn btn-primary my-1" %>
      </div>
      <div>
        <%= link_to "BIO", bios_path, class: "btn btn-warning my-1" %>
      </div>
      <div>
        <%= link_to "CONTACT", contact_path, class: "btn btn-danger my-1" %>
      </div>
      <div>
        <%= link_to "LOGIN", new_user_session_path, class: "btn btn-info my-1" %>
      </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-collapse">
    <%= link_to "JOPENCA.COM", root_path, class: "btn btn-success" %>
    <%= link_to "NEWS", events_path, class: ["btn btn-primary", ("active" if request.path == events_path)] %>
    <%= link_to "BIO", bios_path, class: ["btn btn-warning", ("active" if request.path == bios_path)]%>
    <%= link_to "CONTACT", contact_path, class: ["btn btn-danger", ("active" if request.path == contact_path)] %>
    <% if user_signed_in? %>
      <%= link_to "LOGOUT USER #{current_user&.email}", destroy_user_session_path, method: :delete, class: "btn btn-info" %>
      <% else %>
        <%= link_to "LOGIN", new_user_session_path, class: "btn btn-info" %>
    <% end %>
  </div>
</div>